
SIZE = 10 # GRID SIZE

HM_EPISODES = 100 # MAX EPISODES

STOP_TRAINING_EPISODE = int(0.2*HM_EPISODES) # Stop training other Blobs after

STEP_COUNT = 100 # MAX STEP per EPISODE

SHOW_EVERY = 1 # UPDATE DISPLAY per _ STEP

# LEARNING VARIABLES
EPS_DECAY = 0.9998

LEARNING_RATE = 0.5
DISCOUNT = 0.95

# REWARDS
MOVE_PENALY = 1
OBSTACLE_PENALTY = 50
TRAP_PENALTY = 100
ENEMY_PENALY = 100
FOOD_REWARD = 25

# dict access strings
ENEMY = "enemy"
PLAYER = "player"
FOOD = "food"